name: Bump Version and Publish

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Bump version
      id: bump_version
      run: |
        git config --global user.email "juanjo19089@gmail.com"
        git config --global user.name "jjlmoya"
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        NEW_VERSION=$(npm version minor --no-git-tag-version)
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        git commit -am "chore(release): $NEW_VERSION [skip ci]"
        git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"

    - name: Push changes
      run: |
        git push origin HEAD:main
        git push origin --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
